export const REVIEWS_FETCH = 'REVIEWS_FETCH';
export const REVIEWS_FETCH_SUCCESS = 'REVIEWS_FETCH_SUCCESS';
export const REVIEWS_FETCH_FAIL = 'REVIEWS_FETCH_FAIL';

export const REVIEW_FETCH = 'REVIEW_FETCH';
export const REVIEW_FETCH_SUCCESS = 'REVIEW_FETCH_SUCCESS';
export const REVIEW_FETCH_FAIL = 'REVIEW_FETCH_FAIL';

export const REVIEW_ADD = 'REVIEW_ADD';
export const REVIEW_ADD_SUCCESS = 'REVIEW_ADD_SUCCESS';
export const REVIEW_ADD_FAIL = 'REVIEW_ADD_FAIL';
export const REVIEW_ADD_STATUS = 'REVIEW_ADD_STATUS';

export const REVIEW_EDIT = 'REVIEW_EDIT';
export const REVIEW_EDIT_SUCCESS = 'REVIEW_EDIT_SUCCESS';
export const REVIEW_EDIT_FAIL = 'REVIEW_EDIT_FAIL';

export const REVIEW_REMOVE = 'REVIEW_REMOVE';
export const REVIEW_REMOVE_SUCCESS = 'REVIEW_REMOVE_SUCCESS';
export const REVIEW_REMOVE_FAIL = 'REVIEW_REMOVE_FAIL';